const CFG={wa:"919555083044",email:"vyashikadigital@gmail.com",brand:"Summit & Oak Realty",formspree:"",ga:""};
const $=id=>document.getElementById(id),$$=s=>[...document.querySelectorAll(s)];
let L=[],saved=new Set(),th="dark",lang="en";
try{saved=new Set(JSON.parse(localStorage.getItem("so_saved")||"[]"));lang=localStorage.getItem("so_lang")||"en";th=localStorage.getItem("so_theme")||"dark"}catch(e){}
const store=()=>{try{localStorage.setItem("so_saved",JSON.stringify([...saved]))}catch(e){}};
if(CFG.ga){const s=document.createElement("script");s.async=1;s.src="https://www.googletagmanager.com/gtag/js?id="+CFG.ga;document.head.appendChild(s);window.dataLayer=[];window.gtag=function(){dataLayer.push(arguments)};gtag("js",new Date());gtag("config",CFG.ga)}
async function loadData(){try{const r=await fetch("listings.json",{cache:"no-store"});if(r.ok)L=await r.json()}catch(e){}try{const o=JSON.parse(localStorage.getItem("so_admin_listings")||"null");if(o&&o.length)L=o}catch(e){}}
const money=n=>"$"+Math.round(n).toLocaleString("en-US"),price=x=>x.m==="rent"?money(x.p)+"/mo":money(x.p);
const wa=m=>"https://wa.me/"+CFG.wa+"?text="+encodeURIComponent(m),mail=(s,m)=>"mailto:"+CFG.email+"?subject="+encodeURIComponent(s)+"&body="+encodeURIComponent(m);
const art=h=>`<svg viewBox="0 0 320 200" role="img" aria-label="Property illustration"><rect width="320" height="200" fill="hsl(${h},50%,86%)"/><rect y="150" width="320" height="50" fill="hsl(${h},30%,38%)"/><rect x="70" y="86" width="180" height="70" fill="hsl(${h},25%,96%)"/><polygon points="58,90 160,36 262,90" fill="hsl(${h},45%,28%)"/><rect x="146" y="112" width="28" height="44" fill="hsl(${h},45%,28%)"/></svg>`;
const fb=(el,h)=>{el.outerHTML=art(h)};
const imgUrl=(i,w)=>i.indexOf("http")===0?i:"https://images.unsplash.com/photo-"+i+"?auto=format&fit=crop&w="+(w||800)+"&q=70";
const pic=(x,w)=>x.i?`<img src="${imgUrl(x.i,w)}" alt="${x.t}" loading="lazy" onerror="fb(this,${x.h})">`:art(x.h);
const card=(x,c)=>`<article class="card"><div class="im"><a class="im" href="property.html?id=${x.id}" aria-label="View ${x.t}">${pic(x)}</a><span class="tag">${x.m==="buy"?"For sale":"For rent"}</span><button class="fav" data-fav="${x.id}" aria-pressed="${saved.has(x.id)}" aria-label="Save ${x.t}">&#9829;</button></div><div class="cb"><div class="pr">${price(x)}</div><h3 style="font-size:19px">${x.t}</h3><div class="sp">${x.b} bd &middot; ${x.ba} ba &middot; ${x.s.toLocaleString("en-US")} sqft</div><div class="sp">${x.c} &middot; ${x.y}</div><a class="btn alt" href="property.html?id=${x.id}" style="margin-top:8px">View details</a>${c?`<label class="sp" style="display:flex;gap:8px;align-items:center;margin:6px 0 0"><input type="checkbox" style="width:auto" data-cmp="${x.id}">Compare</label>`:""}</div></article>`;
function favClick(e,done){const f=e.target.closest("[data-fav]");if(!f)return false;const id=+f.dataset.fav;saved.has(id)?saved.delete(id):saved.add(id);store();$("savedNav").textContent="Saved ("+saved.size+")";done&&done();return true}
function tilt(el,k,sel){if(!matchMedia("(hover:hover)").matches)return;const t=e=>sel?e.target.closest(sel):el;el.addEventListener("pointermove",e=>{const c=t(e);if(!c)return;const r=c.getBoundingClientRect();c.style.transform=`perspective(900px) rotateY(${((e.clientX-r.left)/r.width-.5)*k}deg) rotateX(${-((e.clientY-r.top)/r.height-.5)*k}deg)`});el.addEventListener("pointerout",e=>{const c=t(e);if(c&&!c.contains(e.relatedTarget))c.style.transform=""})}
function sendForm(n,p,msg,ch,out){const m="Name: "+n+"\nPhone: "+p+"\n"+msg;
 if(ch==="em"&&CFG.formspree){fetch(CFG.formspree,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({name:n,phone:p,message:msg})}).then(r=>{out.textContent=r.ok?"Thanks, we received your message.":"Could not send. Please use WhatsApp."});return}
 if(ch==="em")location.href=mail("Inquiry from "+n,m);else window.open(wa(m),"_blank","noopener");
 out.textContent="Thanks, "+n+". Your message is ready to send."}
const NAV=["Home","Buy","Rent","Calculator","Guides","About","Contact"],HREF=["index.html","listings.html?m=buy","listings.html?m=rent","calculator.html","guides.html","about.html","contact.html"];
const HI={Home:"होम",Buy:"खरीदें",Rent:"किराये पर",Calculator:"कैलकुलेटर",Guides:"गाइड",About:"हमारे बारे में",Contact:"संपर्क","Homes for sale":"बिक्री के लिए घर","Homes for rent":"किराये के घर","About us":"हमारे बारे में","Buying and renting guides":"खरीदने और किराये की गाइड","Contact us":"हमसे संपर्क करें","Mortgage calculator":"मॉर्गेज कैलकुलेटर"};
$("hdr").innerHTML=`<div class="w"><a class="logo" href="index.html">Summit &amp; Oak Realty</a><nav>${NAV.map((n,i)=>`<a class="nv" data-t href="${HREF[i]}">${n}</a>`).join("")}<button class="chip" id="lng" aria-label="Switch language">हिं</button><button class="chip" id="thm" aria-label="Switch light or dark theme">Theme</button><a class="nv" id="savedNav" href="listings.html?saved=1">Saved (${saved.size})</a></nav></div>`;
$("ftr").innerHTML=`<div class="w fg3"><div><b style="color:#fff">Summit &amp; Oak Realty</b><p>Homes and rentals in six growing U.S. markets. Sample listings for demonstration.</p></div><div><b style="color:#fff">Explore</b><br>${NAV.map((n,i)=>`<a href="${HREF[i]}">${n}</a>`).join(" &middot; ")}</div><div><b style="color:#fff">Talk to us</b><br><a href="${wa("Hi, I have a question about a property.")}">WhatsApp +91 95550 83044</a><br><a href="mailto:${CFG.email}">${CFG.email}</a></div></div><div class="w" style="margin-top:18px">&copy; ${new Date().getFullYear()} Summit &amp; Oak Realty. Website by <a href="https://www.vyashikadigital.com">Vyashika Digital</a>. Photos from <a href="https://unsplash.com">Unsplash</a> contributors. <a href="admin.html">Admin login</a></div>`;
document.body.insertAdjacentHTML("beforeend",`<a class="wab" href="${wa("Hi, I'd like help finding a home.")}" target="_blank" rel="noopener" aria-label="Chat on WhatsApp">Chat on WhatsApp</a>`);
function applyLang(){$$("[data-t]").forEach(e=>{e.dataset.en=e.dataset.en||e.textContent;e.textContent=lang==="hi"&&HI[e.dataset.en]?HI[e.dataset.en]:e.dataset.en});document.documentElement.lang=lang==="hi"?"hi":"en-US";$("lng").textContent=lang==="hi"?"EN":"हिं"}
function applyTheme(){document.documentElement.dataset.theme=th;$("thm").textContent=th==="dark"?"Light":"Dark"}
$("lng").addEventListener("click",()=>{lang=lang==="hi"?"en":"hi";try{localStorage.setItem("so_lang",lang)}catch(e){}applyLang()});
$("thm").addEventListener("click",()=>{th=th==="dark"?"light":"dark";try{localStorage.setItem("so_theme",th)}catch(e){}applyTheme()});
applyTheme();applyLang();
$$("nav a.nv").forEach(a=>{if(a.getAttribute("href")===location.pathname.split("/").pop()+location.search||(a.getAttribute("href")==="index.html"&&!location.pathname.split("/").pop()))a.setAttribute("aria-current","page")});
